default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV.fetch("MYSQL_USER") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: mysql
  port: 3306

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") %>

test:
  <<:
  database: phone_book_test

production:
  <<: *default
  database:  <%= ENV.fetch("MYSQL_DATABASE") %>