default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: my_mysql
  password: welcome1
  host: localhost #mysql
  port: 3306

development:
  <<: *default
  database: my_development

test:
  <<: *default
  database: phone_book_test

production:
  <<: *default
  database:  my_development